***Question 1***

In [51]:
import numpy as np

array = np.random.randint(1, 50, size=(6, 6))
print(array)


[[ 3 24 14 34  6 17]
 [ 6  8  9 47 13 30]
 [13 31 14 17 30 29]
 [ 8  7 22 27 37  4]
 [ 3 10 42 45 16 36]
 [42 21 32  1 26 42]]


***Question 2***

In [52]:
# import numpy as np

# array= np.random.randint(1, 51, (6, 6))
print("Original Array:\n", array)

print("\nFirst two rows:\n", array[:2])

print("\nLast three columns:\n", array[:, 3:])

print("\nEven numbers:\n", array[array % 2 == 0])


Original Array:
 [[ 3 24 14 34  6 17]
 [ 6  8  9 47 13 30]
 [13 31 14 17 30 29]
 [ 8  7 22 27 37  4]
 [ 3 10 42 45 16 36]
 [42 21 32  1 26 42]]

First two rows:
 [[ 3 24 14 34  6 17]
 [ 6  8  9 47 13 30]]

Last three columns:
 [[34  6 17]
 [47 13 30]
 [17 30 29]
 [27 37  4]
 [45 16 36]
 [ 1 26 42]]

Even numbers:
 [24 14 34  6  6  8 30 14 30  8 22  4 10 42 16 36 42 32 26 42]


***Question 3***

In [ ]:
array = np.arange(36)

reshaped = array.reshape(3, 2, 6)

flattened = reshaped.flatten()

print("Reshaped array:\n", reshaped)
print("\nFlattened array:\n", flattened)



Reshaped array:
 [[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]]

Flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


***Question 4***

In [1]:
import numpy as np
# Generate 4x4 identity matrix
matrix = np.identity(4, dtype=int)
# Replace diagonal with [10, 20, 30, 40]
matrix[np.arange(4), np.arange(4)] = np.arange(10, 41, 10)
print("Modified 4x4 Matrix:")
print(matrix)

Modified 4x4 Matrix:
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


***Question 5***

In [2]:
# Generate random 3x4 and 4x3 matrices with integers 1–10
A = np.random.randint(1, 11, size=(3, 4))
B = np.random.randint(1, 11, size=(4, 3))
# Perform matrix multiplication
C = np.dot(A, B)
print("Matrix A (3x4):")
print(A)
print("\nMatrix B (4x3):")
print(B)
print("\nResultant Matrix C (3x3):")
print(C)








Matrix A (3x4):
[[ 4  8  2  1]
 [10  2  1  9]
 [ 1  5  9  7]]

Matrix B (4x3):
[[ 4 10  9]
 [ 4  9  5]
 [ 3  1  2]
 [ 2  1  4]]

Resultant Matrix C (3x3):
[[ 56 115  84]
 [ 69 128 138]
 [ 65  71  80]]


***Question 6***

In [3]:
import numpy as np

def transform_array(arr):
    # Create a copy to avoid modifying the original array
    result = np.copy(arr)
    
    # Apply transformation: square even numbers, replace odd numbers with -1
    even_mask = (result % 2 == 0)
    odd_mask = ~even_mask
    
    result[even_mask] = result[even_mask] ** 2
    result[odd_mask] = -1
    
    return result

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(transform_array(arr))


[[-1  4 -1]
 [16 -1 36]]
