***Question 1***

In [51]:
import numpy as np

array = np.random.randint(1, 50, size=(6, 6))
print(array)


[[ 3 24 14 34  6 17]
 [ 6  8  9 47 13 30]
 [13 31 14 17 30 29]
 [ 8  7 22 27 37  4]
 [ 3 10 42 45 16 36]
 [42 21 32  1 26 42]]


***Question 2***

In [52]:
# import numpy as np

# array= np.random.randint(1, 51, (6, 6))
print("Original Array:\n", array)

print("\nFirst two rows:\n", array[:2])

print("\nLast three columns:\n", array[:, 3:])

print("\nEven numbers:\n", array[array % 2 == 0])


Original Array:
 [[ 3 24 14 34  6 17]
 [ 6  8  9 47 13 30]
 [13 31 14 17 30 29]
 [ 8  7 22 27 37  4]
 [ 3 10 42 45 16 36]
 [42 21 32  1 26 42]]

First two rows:
 [[ 3 24 14 34  6 17]
 [ 6  8  9 47 13 30]]

Last three columns:
 [[34  6 17]
 [47 13 30]
 [17 30 29]
 [27 37  4]
 [45 16 36]
 [ 1 26 42]]

Even numbers:
 [24 14 34  6  6  8 30 14 30  8 22  4 10 42 16 36 42 32 26 42]


***Question 3***

In [ ]:
array = np.arange(36)

reshaped = array.reshape(3, 2, 6)

flattened = reshaped.flatten()

print("Reshaped array:\n", reshaped)
print("\nFlattened array:\n", flattened)



Reshaped array:
 [[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]]

Flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


***Question 4***